# Numpy 

# Name: Kumar R.

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [1]:
import numpy as np #importing the numpy

In [2]:
#defining a function named vander_matrix
def vander_matrix(ipvector, column, increasing=True): 
    if not increasing:
        matrix_out = np.array([x**(column-i-1) for x in ipvector for i in range(column)]).reshape(ipvector.size, column)
    else:
        matrix_out = np.array([x**i for x in ipvector for i in range(column)]).reshape(ipvector.size, column)
    return matrix_out


In [3]:
ipvect = np.array([1,2,3,4,5])
columns = 3
output_increase = vander_matrix(ipvect,columns, True) #creating a matrix in increasing order.
output_decrease = vander_matrix(ipvect, columns, False) #creating a matrix in decreasing order.
print("Input values:") #printing the input values
print("Input array vector: ",ipvect,"\n")
print("Number of columns in the output matrix: ",columns)

print("-"*30,"\n")
print("Output:") #Printing the outut values
print("The vander matrix of the input array vector in increasing order is:  \n",output_increase)
print()
print("The vander matrix of the input array vector in decreasing order is: \n", output_decrease)

Input values:
Input array vector:  [1 2 3 4 5] 

Number of columns in the output matrix:  3
------------------------------ 

Output:
The vander matrix of the input array vector in increasing order is:  
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]

The vander matrix of the input array vector in decreasing order is: 
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


Writing a function to find moving average in an array over a window 3.

In [4]:
#defining a function to find the moving average of an array.
def moving_average(array, k=3) :
    avg = np.cumsum(array, dtype=float)
    avg[k:] = avg[k:] - avg[:-k]
    return avg[k - 1:] / k

In [5]:
ar = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
out = moving_average(ar)

print('Input array vector is: ',ar,"\n")

print("Moving average: ",out)

Input array vector is:  [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 

Moving average:  [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
